spring.application.name=exam

spring.datasource.url=jdbc:h2:mem:examtestdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=chad
spring.datasource.password=kab

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console